name: Build and Release CMake on Windows

on:
  push:
    tags:
      - 'v*.*.*' # Ex: v1.0.0

permissions:
  contents: write

env:
  version: 1.0.0

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout do repositório
      uses: actions/checkout@v4

    - name: 🧰 Configurar CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: 🧱 Compilar projeto
      run: cmake --build build --config Release

    - name: 📤 Criar Release no GitHub
      uses: softprops/action-gh-release@v2
      with:
        name: "Thermall v${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: build/Release/Thermall.exe
